# 메인페이지용 deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      page: main
  template:
    metadata:
      name: pod-main
      labels:
        page: main
    spec:
      containers:
      - name: ctn-main
        image: jhk950425/testweb:testhome
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 750m
          requests:
            cpu: 250m
        volumeMounts:
        - name: nfs-volume
          mountPath: /backup
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: pod-pvc
---
# 메인페이지용 서비스
apiVersion: v1
kind: Service
metadata:
  name: svc-main
spec:
  selector:
    page: main
  ports:
  - port: 80
---
# blog deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      page: blog
  template:
    metadata:
      name: pod-blog
      labels:
        page: blog
    spec:
      containers:
      - name: ctn-blog
        image: jhk950425/testweb:testblog
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 125m
        volumeMounts:
        - name: nfs-volume
          mountPath: /backup
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: pod-pvc
---
# blog 서비스
apiVersion: v1
kind: Service
metadata:
  name: svc-blog
spec:
  selector:
    page: blog
  ports:
  - port: 80
---
# shop deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      page: shop
  template:
    metadata:
      name: pod-shop
      labels:
        page: shop
    spec:
      containers:
      - name: ctn-shop
        image: jhk950425/testweb:testshop
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        volumeMounts:
        - name: nfs-volume
          mountPath: /backup
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: pod-pvc
---
# shop 서비스
apiVersion: v1
kind: Service
metadata:
  name: svc-shop
spec:
  selector:
    page: shop
  ports:
  - port: 80
---
