---
apiVersion: v1
kind: Namespace
metadata:
  name: samsung
---
apiVersion: apps/v1

kind: Deployment

metadata:
  name:	deploy-ss
  namespace: samsung
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ss-pods-label
  template:
    metadata:
      name: my-ss-pod
      labels:
        app: my-ss-pods-label
    spec:
      containers:
      - name: ss
        image: jhk950425/testweb:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: ss-lb
  namespace: samsung
spec:
  ports:
  - name: ss-port
    targetPort: 80 
    port: 80
    # nodePort: 31008
  selector: 
    app: my-ss-pods-label
  type: LoadBalancer
