apiVersion: v1
kind: Pod 
metadata: 
  name: vol-test 
spec: 
  containers: 
  - name: my-vol 
    image: nginx 
    volumeMounts: 
    - name: configmap-volume 
      mountPath: /etc/config 

  volumes:
  - name: configmap-volume 
    configMap: 
      name: test1-cmap    
